version: '3.1'

services:
  db:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_PASSWORD: datcom
      POSTGRES_DB: datcom
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
